### ISSUE TITLE
Job definitions

### ISSUE THREAD

**Issue by StanSvec** [taro-suite/taro#51]
Each job could optionally have its definition in a new configuration file called `jobs.yaml` stored in the config directory. This would provide an alternative way how to specify execution parameters. Another usage is to define some constant arguments for a job. We can call them `properties`. They are similar to execution parameters, but these parameters can differ each execution whereas the properties are constant for multiple executions and don't need to be stored in taro DB.

The first proposal of the new yaml file:
```
this_is_a_job_id:
    properties:
        arg1: value1
        arg2: value2
```
